[package]
name = "log"
version = "0.7.3"
edition = "2024"
authors = ["hardglitch"]

[dependencies]
time = { version = "0.3", features = ["macros", "formatting"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
indexing_slicing = "warn"
arithmetic_side_effects = "warn"
